<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * Overload findAll().
     *
     * @return array
     */
    public function findAll()
    {
        return $this->findBy([], ['createdAt' => 'DESC', 'id' => 'DESC']);
    }
}
