# Security (must be first to avoid conflicts with badly defined routes)
# ========

security_login_check:
    methods: POST
    path: /security/login_check

security_logout:
    methods: GET
    path: /security/logout

# Bundles
# =======

# Application Programming Interface
# ---------------------------------

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

# Application
# -----------

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

