users:
    resource: ApiBundle\Controller\UsersController
    type:     rest

users_articles:
    parent:   users
    resource: ApiBundle\Controller\ArticlesController
    type:     rest

users_images:
    parent:   users
    resource: ApiBundle\Controller\ImagesController
    type:     rest